apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: desafio
data:
  POSTGRES_DB: appdb
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-config
  namespace: desafio
data:
  PGRST_DB_SCHEMAS: "public"
  PGRST_DB_ANON_ROLE: "admin"
  PGRST_ADMIN_SERVER_PORT: "3001"
