apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: desafio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:v12.2.3
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: PGRST_DB_URI
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)\
                @postgres:5432/$(POSTGRES_DB)"
            - name: PGRST_DB_SCHEMAS
              valueFrom:
                configMapKeyRef:
                  name: postgrest-config
                  key: PGRST_DB_SCHEMAS
            - name: PGRST_DB_ANON_ROLE
              valueFrom:
                configMapKeyRef:
                  name: postgrest-config
                  key: PGRST_DB_ANON_ROLE
            - name: PGRST_ADMIN_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgrest-config
                  key: PGRST_ADMIN_SERVER_PORT
          livenessProbe:
            httpGet:
              path: /live
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
